version: '3.8'

services:
  mysql-server:
    image: mysql/mysql-server:latest
    environment:
      MYSQL_ROOT_PASSWORD: walid#00
    networks:
      - tooling_app_network
    hostname: mysqlserverhost
    container_name: mysql-server

  tooling:
    image: walidali123/my-repo:1.1.0
    ports:
      - "8085:80"
    networks:
      - tooling_app_network

networks:
  tooling_app_network:
    external: true

 